module.exports = 
  {
    title: "Sobre Nós",
    story_title: "A Empresa",
    story: "Fundada em Outubro de 1995, a empresa Alcoplano - Planeamento e Construções, Lda., assume a forma de sociedade por quotas, sendo o objecto principal a Construção Civil e Obras Públicas; com sede no Concelho de Alcobaça, procura desenvolver a sua actividade em todo o território Nacional, com particular incidência na Região de Lisboa e Vale do Tejo.<br>Tem-se afirmado, ao longo dos anos, como uma empresa construtora fortemente vocacionada para o sector habitacional de obras Públicas e Privadas, assente no lema:  “A qualidade não é para nós uma obrigação, é um grande prazer”.<br>No sector de recuperação e conservação de património, a Alcoplano pretende posicionar-se com particular destaque, pois, tem nos seus quadros colaboradores de elevada competência, originários da área da sua sede, cuja região possui uma forte e sólida tradição na formação de profissionais nesta área.<br>Neste contexto, a Alcoplano tem desenvolvido diversos trabalhos de restauro, nomeadamente na área urbana de Lisboa - Bairro Alto quer no sector particular, quer público, desfrutando de capacidade técnica e logística para executar qualquer tipo de empreitada, de acordo com as suas habilitações.<br><br>Contando com uma vasta experiência no mercado nacional, e aproveitando as sinergias criadas ao longo da sua actividade, e através da Sua participada Alcoplano Imobiliária, Lda constituída em 2006, desenvolveu a sua actividade na área Imobiliária, não só para o mercado interno como também para o mercado externo tendo assumido nos últimos anos na n/ empresa uma percentagem relevante da n/ actividade, quer na venda de imóveis construídos para revenda quer na construção em regime de empreitada, na qual se destacam entre outros o mercado Inglês, Irlandês e Belga.<br>Neste momento contamos com um quadro técnico qualificado e competente, fazendo de nós uma empresa competitiva e credível no mercado, orientados para uma evolução e melhoria contínua de forma a responder ás exigências dos nosso clientes, conforme poderá ser verificado junto dos mesmos relacionados em documento anexo.<br>Alcoplano tem como principal missão atingir os níveis de qualidade que satisfaçam os seus clientes, bem como o cumprimento dos prazos exigidos e preços competitivos, apostando e assumindo sempre uma postura de diálogo com os clientes e seus representantes, no sentido de dar resposta ao seus reais objectivos.<br><br>Perante os seus clientes e fornecedores a Alcoplano quer ser vista como uma empresa digna e cumpridora dos seus compromissos, tendo conseguido assim que os nossos principais aliados e divulgadores do nosso trabalho são os próprios clientes.",
    mission_title: "A Missão",
    mission: "Alcoplano tem como principal missão atingir os níveis de qualidade que satisfaçam os seus clientes, bem como o cumprimento dos prazos exigidos e preços competitivos, apostando e assumindo sempre uma postura de diálogo com os clientes e seus representantes, no sentido de dar resposta ao seus reais objectivos.",
    certification_title: "Certificações",
    certification: "A Alcoplano, Lda., encontra-se inscrita no InCI, I.P. (Instituto da Construção e do Imobiliário, I.P.), desde 19/06/1996, onde é detentora do alvará de construção n.º 24901, possuindo para o efeito as seguintes habilitações:<br><br><b>1ª Categoria-Edificio e Património</b><br>Empreiteiro geral de Construção Tradicional            -classe 4<br>Empreiteiro geral de Estrutura Metálica                -classe 3<br>Empreiteiro geral de Edifícios de Madeira            -classe 3<br>Empreiteiro geral de reabilitação e Conserv. de Edificios    -classe 3<br><br>Detentora das Subcategorias             1ª,2ª,3ª,4ª,5ª,6ª,7ª,8ª,9ª<br><br><b>2ª Categoria-Vias de Comunicação,Urbanismo e Infra-estrutruturas</b><br>Detentora das Subcategorias                 6ª,8ª,9ª,10ª<br><br> <br><b>5ª Categoria-Outros Trabalhos</b><br>Detentora das Subcategorias         1ª,2ª,7ª,8ª,9ª,10ª,11ª,12ª,13ª",
    caption: "A qualidade não é para nós uma obrigação,<br> é um grande prazer",
    side_nav: {
      company: "Empresa",
      mission: "Missão",
      certification: "Certificação"
    }
}
